### ISSUE TITLE
non-cluster rds snasphots are not supported

### ISSUE THREAD

**Issue by awasilyev** [binbashar/terraform-aws-rds-export-to-s3#5]
I guess it is needed to add 
"RDS DB Snapshot Event" in addition to "RDS DB Cluster Snapshot Event"

**Comment by exequielrafaela** [comment]
@awasilyev Hey, thanks for creating this issue. Could you please give us some more context so we can help you? Are you getting any specific errors with the current module?

**Comment by awasilyev** [comment]
It is pretty simple, I'm trying to use it for non-cluster rds db instance
and it is not working. I'm trying to do a fix currently on a forked repo.

**Comment by exequielrafaela** [comment]
@awasilyev I see your point now. And you're right. This was by design because we've been mainly using this module for RDS Aurora Clusters snapshots. But it totally makes sense to support non-cluster RDS instances like RDS Mysql or RDS Postgres. Many thanks for your feedback and collaboration, and we look forward to your PR 💪🏼 

CC: @binbashar/leverage-project-terraform-admin @binbashar/leverage-project-terraform-dev

**Comment by awasilyev** [comment]
https://github.com/binbashar/terraform-aws-rds-export-to-s3/pull/6

**Comment by exequielrafaela** [comment]
https://github.com/binbashar/terraform-aws-rds-export-to-s3/releases/tag/v0.4.0
